version: 0.2

phases:
  install:
    runtime-versions:
       nodejs: 8
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=${REPLACE_WITH-AWS_ACCOUNTID}.dkr.ecr.us-gov-west-1.amazonaws.com/cyber-eval
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=dev}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:dev .
      - docker tag $REPOSITORY_URI:dev $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:dev
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
artifacts:
  files:
     - '**/*'
  name: s3-to-s3-dev-build.zip